(define nil '())
(define x (list (list 1 (list 2 8 5)) (list 3 4)))
(define (deep-reverse items)
  (define (deep-reverse-if-required may-be-items)
    (if (pair? may-be-items)
        (iter may-be-items nil)
        may-be-items))
  (define (iter items-remained items-reversed)
    (if   (null? items-remained)
          items-reversed
          (iter (cdr items-remained)
                      (cons (deep-reverse-if-required (car items-remained))
                            items-reversed))))
  (iter items nil))
(deep-reverse x)