(define (mult a b)
  (define (double x) (* x 2))
  (define (halve x) (/ x 2))
  (define (even? x) (= (remainder x 2) 0))
  (cond ((= b 0) 0)
        ((even? b) (mult (double a) (halve b)))
        (else (+ a (mult a (- b 1))))))
(trace-entry mult)