(define (simpson f a b n)
  (define h (/ (- b a) n))
  (define (y k) (f (+ a (* k h))))
  (define (factor k)
    (cond ((or (= k 0) (= k n)) 1.0)
          ((= 0 (remainder k 2)) 2.0)
          (else 4.0)))
  (define (next k) (+ k 1))
  (define (term k)
    (* (factor k) (y k)))
  (define (iter k sum)
    (cond ((> k n) sum)
          ((iter (next k) (+ sum (term k))))))
  (/ (* (iter 0 0) h) 3))
(define (cube x) (* x x x))
(simpson cube 0 1 1000)